if (! document.localization) document.localization = [];

document.localization ['id_ID'] = {
    'login.username': 'Nama pengguna atau email',
    'login.username.placeholder': 'Masukkan nama pengguna atau email Anda',
    'login.password': 'Kata sandi:',
    'login.password.placeholder': 'Masukkan kata sandi',
    'login.submit': 'Masuk',
    'login.password.incorrect': 'Nama pengguna atau kata sandi tidak valid',
    'login.password.recovery': 'Lupa kata sandi?',
    'recovery.password': 'Pulihkan kata sandi',
    'recovery.password.success': 'Petunjuk pemulihan kata sandi telah dikirim ke email Anda',
    'login.no.account': 'Belum punya akun?',
    'login.signup': 'Daftar',

    'signup.title': 'Mulai',
    'signup.email': 'Alamat email Anda',
    'signup.email.placeholder': 'Masukkan alamat email yang valid',
    'signup.email.invalid': 'Masukkan alamat email yang valid',
    'signup.terms.agree': 'Saya setuju dengan',
    'signup.terms.terms': 'syarat dan ketentuan',
    'signup.submit': 'Daftar',
    'signup.progress': 'Mendaftar...',
    'signup.email.used': 'Pelanggan dengan email ini sudah terdaftar',
    'signup.name.used': 'Pelanggan dengan nama pengguna ini sudah terdaftar',
    'signup.complete': 'Terima kasih telah mendaftar!',
    'signup.email.check': 'Periksa email Anda dan ikuti tautannya untuk menyelesaikan pendaftaran!',
    'signup.complete.title': 'Akun Anda di ${appName} hampir siap!',
    'signup.ready.title': 'Akun Anda di ${appName} sudah siap!',
    'signup.customer.id': 'Nama pengguna',
    'signup.customer.id.placeholder': 'Gunakan huruf dan angka saja',
    'signup.customer.id.invalid': 'Gunakan 6 karakter atau lebih, hanya huruf dan angka',
    'signup.first.name': 'Nama depan',
    'signup.first.name.placeholder': 'Nama depan Anda (wajib)',
    'signup.last.name': 'Nama belakang',
    'signup.last.name.placeholder': 'Nama belakang Anda (wajib)',
    'signup.company': 'Nama perusahaan',
    'signup.company.placeholder': 'Nama bisnis Anda (opsional)',
    'signup.description': 'Bagaimana Anda akan menggunakan MDM?',
    'signup.description.placeholder': 'Ini akan membantu tim kami membantu Anda',
    'signup.password': 'Kata sandi',
    'signup.password.repeat': 'Ulangi kata sandi',
    'signup.password.placeholder': '6+ karakter',
    'signup.password.short': 'Masukkan minimal 6 karakter',
    'signup.password.not.match': 'Kata sandi tidak cocok',
    'signup.finalized.title': 'Akun Anda sudah siap!',
    'signup.finalized.description': 'Dalam waktu singkat, Anda akan menerima email berisi petunjuk berguna. Silakan tinjau email ini dan masuk ke panel web menggunakan nama pengguna dan kata sandi Anda.',
    'signup.token.invalid.title': 'Token tidak valid atau sudah digunakan',
    'signup.token.invalid.description': 'Silakan coba daftar lagi untuk membuat akun baru!',

    'header.label.username': 'Nama pengguna',

    'summary.devices.status': 'Status perangkat',
    'summary.devices.active': 'Aktif',
    'summary.devices.idle': 'Diam',
    'summary.devices.offline': 'Luring',
    'summary.devices.enrollment': 'Ringkasan pendaftaran',
    'summary.devices.enrolled.total': 'Total terdaftar',
    'summary.devices.enrolled.earlier': 'Terdaftar sebelumnya',
    'summary.devices.enrolled.monthly': '30 hari terakhir',
    'summary.devices.installation.status': 'Status aplikasi',
    'summary.devices.installation.completed': 'Selesai',
    'summary.devices.version.mismatch': 'Versi tidak cocok',
    'summary.devices.installation.failed': 'Pemasangan gagal',
    'summary.devices.enrolled.lastyear': '12 bulan terakhir',

    'devices.group.options.all': 'Semua grup',
    'devices.configuration.options.all': 'Semua konfigurasi',
    'devices.permissions.all': 'Semua izin telah diberikan',
    'devices.permissions.not.as.device.admin': '- Aplikasi tidak dipasang sebagai administrator perangkat',
    'devices.permissions.window.overlap.prohibited': '- Overlay di atas jendela lain tidak tersedia',
    'devices.permissions.history.access.prohibited': '- Akses ke riwayat penggunaan belum dikonfigurasi',
    'devices.unknown': 'Tidak diketahui',
    'devices.model.unknown': 'Tidak diketahui',
    'devices.date.unknown': 'tidak diketahui',
    'devices.date.format': 'dd/MM/yy HH:mm',
    'devices.app.installed': '- ${applicationName}: Terpasang.',
    'devices.app.not.installed': '- ${applicationName}: tidak terpasang.',
    'devices.app.version.available': ', tersedia ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: terpasang ${applicationInstalledVersion}, tersedia ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion}, perlu dihapus',
    'devices.no.data': 'Perangkat belum mengirimkan data',
    'devices.settings.conformance.broken': 'Tidak cocok dengan pengaturan: (${serverData})',
    'devices.file.installed': '- ${file}: terpasang',
    'devices.file.not.installed': '- ${file}: tidak terpasang.',
    'devices.file.lastUpdate.differs': '- ${file}: perbedaan waktu modifikasi ${diff} mnt',

    'button.apply': 'Terapkan',
    'button.gps.on': 'Aktifkan GPS',
    'button.wifi.on': 'Aktifkan Wi-Fi',
    'button.notify.update': 'Beri tahu saat pembaruan',
    'button.app.settings': 'Pengaturan aplikasi',
    'button.installed.apps': 'Aplikasi terinstal',
    'device.installed.apps.title': 'Aplikasi terinstal',
    'device.installed.apps.loading': 'Memuat aplikasi…',
    'device.installed.apps.search': 'Cari berdasarkan nama atau paket',
    'device.installed.apps.system.show': 'Tampilkan app sistem',
    'device.installed.apps.empty': 'Belum ada aplikasi yang dilaporkan untuk perangkat ini.',
    'device.installed.apps.col.name': 'Nama',
    'device.installed.apps.col.package': 'Paket',
    'device.installed.apps.col.version': 'Versi',
    'device.installed.apps.col.type': 'Tipe',
    'device.installed.apps.type.system': 'Sistem',
    'device.installed.apps.type.user': 'Pengguna',
    'button.app.usage': 'Aktivitas aplikasi',
    'button.device.command.lock': 'Kunci perangkat',
    'button.device.command.reboot': 'Boot ulang perangkat',
    'button.device.command.wipe': 'Reset pabrik',
    'device.appusage.title': 'Aktivitas aplikasi',
    'device.appusage.loading': 'Memuat aktivitas…',
    'device.appusage.current': 'Sedang / terakhir dibuka',
    'device.appusage.empty': 'Belum ada aktivitas aplikasi. Berikan izin akses-penggunaan di perangkat untuk mengaktifkannya.',
    'device.appusage.col.time': 'Waktu',
    'device.appusage.col.name': 'Aplikasi',
    'device.appusage.col.package': 'Paket',
    'button.ok': 'OK',
    'button.help': 'Bantuan',
    'button.new.app': 'Aplikasi baru',
    'button.new.app.version': 'Versi baru',
    'button.upgrade': 'Tingkatkan',
    'button.renew.config': 'Perbarui di perangkat',
    'button.common': 'Aplikasi umum',
    'button.close': 'Tutup',
    'button.yes': 'Ya',
    'button.cancel': 'Batal',
    'button.save': 'Simpan',
    'button.save.and.close': 'Simpan dan tutup',
    'button.more': 'Lainnya ...',
    'button.cleanup': 'Bersihkan',
    'button.add': 'Tambah',
    'button.add.icon': 'Ikon Baru',
    'button.search': 'Cari',
    'button.export': 'Ekspor',
    'button.change': 'Ubah',
    'button.copy': 'Salin',
    'button.qrcode': 'Kode QR',
    'button.application': 'Aplikasi',
    'button.change.password': 'Ubah kata sandi',
    'button.set.configuration': 'Atur konfigurasi',
    'button.set.group': 'Atur grup',
    'button.group.action': 'Tindakan grup',
    'button.delete': 'Hapus',
    'button.login': 'Masuk',
    'button.renew.code': 'Perbarui',
    'button.configurations': 'Konfigurasi',
    'button.set.configurations': 'Tentukan Konfigurasi',
    'button.edit.versions': 'Versi',
    'button.edit': 'Ubah',
    'button.change.common.app': 'Ubah Aplikasi Bersama',
    'button.delete.common.app': 'Hapus Aplikasi Bersama',
    'button.turn.common.app': 'Jadikan Umum',
    'button.hints.enable': 'Tampilkan tooltip',
    'button.hints.disable': 'Sembunyikan tooltip',
    'button.show.password': 'Tampilkan kata sandi',
    'button.hide.password': 'Sembunyikan kata sandi',

    'question.impersonate.user': 'Masuk ke aplikasi sebagai administrator organisasi "${customerName}"?',
    'question.change.user': 'Masuk ke aplikasi sebagai pengguna "${userName}"?',
    'question.delete.file': 'Hapus berkas "${fileName}"?',
    'question.delete.customer': 'Hapus organisasi "${customerName}"?',
    'question.delete.user': 'Hapus pengguna "${username}"?',
    'question.delete.application': 'Hapus aplikasi "${applicationName}"?',
    'question.delete.application.version': 'Hapus versi "${applicationVersion}"?',
    'question.delete.configuration': 'Hapus konfigurasi "${configurationName}"?',
    'question.delete.group': 'Hapus grup "${groupName}"?',
    'question.delete.role': 'Hapus peran "${roleName}"?',
    'question.delete.icon': 'Hapus ikon "${iconName}"?',
    'question.delete.device.bulk': 'Hapus perangkat yang dipilih?',
    'question.delete.device': 'Hapus perangkat dengan nomor "${deviceNumber}"?',
    'question.device.command': 'Kirim perintah "${command}" ke perangkat "${deviceNumber}"?',
    'question.device.command.wipe.final': 'Reset pabrik akan menghapus semua data pada perangkat "${deviceNumber}". Anda benar-benar yakin?',
    'success.device.command.sent': 'Perintah sudah dikirim ke perangkat.',
    'question.exit.without.saving': 'Perubahan belum disimpan. Tetap tinggalkan halaman ini?',
    'question.turn2common.application': 'Bagikan aplikasi "${applicationName}"?',
    'question.app.upgrade': 'Perbarui aplikasi "${v1}" ke versi terbaru untuk konfigurasi "${v2}"?',

    'error.application.setting.empty.app': 'Tentukan aplikasi',
    'error.application.setting.empty.name': 'Masukkan nama',
    'error.application.setting.empty.value': 'Tentukan nilai',

    'error.icon.dimension.invalid': 'Ikon harus berbentuk persegi',
    'error.icon.empty.name': 'Masukkan nama ikon',
    'error.icon.empty.file': 'Unggah berkas ikon',
    'error.application.version.pkg.mismatch': 'ID paket berkas (${actual}) tidak sesuai dengan aplikasi (${expected})',
    'error.empty.user': 'Pilih pengguna',
    'error.empty.user.name': 'Isi nama pengguna',
    'error.empty.user.login': 'Isi login pengguna',
    'error.empty.user.role': 'Pilih peran pengguna',
    'error.empty.password': 'Masukkan kata sandi baru',
    'error.empty.password.confirm': 'Masukkan konfirmasi kata sandi',
    'error.user.not.found': 'Pengguna tidak ditemukan',
    'error.email.not.configured': 'Email belum dikonfigurasi',
    'error.email.not.found': 'Email pengguna belum diatur',
    'error.empty.group.name': 'Isi nama grup',
    'error.empty.configuration': 'Tentukan konfigurasi',
    'error.empty.configuration.name': 'Isi nama konfigurasi',
    'error.empty.configuration.password': 'Isi kata sandi',
    'error.empty.configuration.contentApp': 'Aplikasi konten belum ditentukan',
    'error.empty.group': 'Tambahkan perangkat ke satu grup atau lebih',
    'error.invalid.character': 'Nomor perangkat tidak boleh mengandung simbol / ? &',
    'error.invalid.configuration.mainApp': 'Pada pengaturan MDM, aplikasi utama yang digunakan salah',
    'error.invalid.configuration.contentApp': 'Aplikasi konten yang digunakan pada pengaturan MDM tidak valid',
    'error.mismatch.password': 'Kata sandi dan konfirmasi kata sandi harus cocok',
    'error.empty.customer.name': 'Isi nama organisasi',
    'error.empty.customer.prefix': 'Isi prefiks nomor perangkat',
    'error.empty.customer.device.configuration': 'Pilih konfigurasi perangkat',
    'error.empty.customer.duplicate.prefix': 'Prefiks sudah digunakan',
    'error.duplicate.customer.name': 'Organisasi dengan nama tersebut sudah ada. Coba nama lain.',
    'error.duplicate.group.name': 'Grup dengan nama tersebut sudah ada. Coba nama lain.',
    'error.duplicate.configuration.name': 'Konfigurasi dengan nama tersebut sudah ada. Coba nama lain.',
    'error.duplicate.device.number': 'Perangkat dengan nomor ini sudah ada',
    'error.internal.server': 'Kesalahan internal server',
    'error.permission.denied': 'Tidak ada hak untuk menjalankan',
    'error.request.failure': 'Permintaan gagal',
    'error.configuration.device.use': 'Tidak dapat menghapus konfigurasi ini karena digunakan pada perangkat. Buka "Perangkat" terlebih dahulu, temukan perangkat yang memakai konfigurasi ini dan ubah pengaturannya.',
    'error.invalid.system.update.time': 'Interval pemasangan tidak valid',
    'error.size.limit.exceeded': 'Batas penyimpanan terlampaui',

    'error.configuration.file.empty.name': 'Masukkan nama berkas',
    'error.configuration.file.empty.desc': 'Tentukan deskripsi berkas',
    'error.configuration.file.empty.path': 'Tentukan path pada perangkat',
    'error.configuration.file.empty.file': 'Silakan unggah berkas',
    'error.configuration.file.empty.url': 'Silakan tentukan URL berkas',

    'error.notfound.device': 'Perangkat tidak ditemukan',
    'error.duplicate.device': 'Perangkat dengan nomor yang sama sudah ada',
    'error.duplicate.login': 'Login tersebut sudah digunakan',
    'error.duplicate.email': 'Pengguna dengan email ini sudah ada',
    'error.duplicate.group': 'Grup dengan nama yang sama sudah ada',
    'error.duplicate.application': 'Aplikasi dengan ID paket dan versi ini sudah ada',
    'error.recent.application.version.exists': 'Versi aplikasi yang lebih baru sudah ada',
    'error.common.application.access.prohibited': 'Pengelolaan aplikasi bersama hanya diizinkan untuk Super-Administrator',
    'error.application.config.reference.exists': 'Aplikasi digunakan pada konfigurasi dan tidak dapat dihapus',
    'error.application.version.deletion.prohibited': 'Versi tersebut unik atau digunakan pada konfigurasi dan tidak dapat dihapus',
    'error.duplicate.file': 'Berkas dengan nama yang sama sudah ada',
    'error.used.file': 'Berkas ini sedang digunakan',
    'error.version.exists': 'Versi aplikasi ini yang sama sudah ada',
    'error.duplicate.configuration': 'Konfigurasi dengan nama ini sudah ada',
    'error.duplicate.role.name': 'Peran dengan nama yang sama sudah ada',
    'error.empty.role.name': 'Silakan tentukan nama peran',
    'error.duplicate.icon.name': 'Ikon dengan nama yang sama sudah ada',
    'error.notfound.customer.admin': 'Akun administrator tidak ditemukan',
    'error.apk.file.required': 'Pilih berkas dengan ekstensi .apk atau .xapk',
    'error.apk.parse': 'Terjadi kesalahan saat mengurai berkas',
    'error.package.not.match': 'ID paket tidak cocok',
    'error.empty.app.name': 'Masukkan nama aplikasi',
    'error.empty.app.pkg': 'Masukkan ID paket',
    'error.empty.app.url': 'Masukkan URL',
    'error.empty.app.iconText': 'Masukkan teks ikon',
    'error.empty.app.version': 'Masukkan versi aplikasi',
    'error.notempty.group': 'Grup ini berisi satu perangkat atau lebih. Anda tidak dapat menghapusnya.',
    'error.file.empty': 'Unggah berkas baru',
    'error.file.deletion': 'Kesalahan saat menghapus berkas di server',
    'error.file.save': 'Kesalahan saat menyimpan berkas di server',
    'error.password.wrong': 'Kata sandi tidak valid',
    'error.password.empty': 'Kata sandi belum ditentukan',
    'error.password.weak': 'Kualitas kata sandi lemah',
    'error.params.missing': 'Parameter yang hilang:',
    'error.empty.push.options': 'Silakan pilih opsi notifikasi Push',
    'error.device.command.unsupported': 'Perintah perangkat tidak didukung',
    'error.app.name.exists': 'Aplikasi lain dengan nama ini sudah ada. Silakan tentukan nama yang unik.',

    'table.filtering.check.all': 'Pilih Semua',
    'table.filtering.uncheck.all': 'Batalkan Semua',
    'table.filtering.suffix.configuration': 'konfigurasi',
    'table.filtering.suffix.group': 'grup',
    'table.filtering.suffix.permission': 'izin',
    'table.filtering.no.selected.configuration': 'Tidak ada konfigurasi dipilih',
    'table.filtering.no.selected.group': 'Tidak ada grup dipilih',
    'table.filtering.no.selected.permission': 'Tidak ada izin dipilih',

    'success.admin.created': 'Akun administrator dibuat:\n ${adminCredentials}',
    'success.uploading.file': 'Berkas sedang diunggah ke server ...',
    'success.loading.devices': 'Memuat daftar perangkat ...',
    'success.loading.customer': 'Memuat detail pelanggan ...',
    'success.file.uploaded': 'Berkas berhasil diunggah.',
    'success.file.uploaded.need.save': 'Berkas berhasil diunggah. Masukkan path relatif dan klik "Simpan".',
    'success.settings.design.saved': 'Pengaturan desain berhasil disimpan',
    'success.settings.common.saved': 'Pengaturan tabel perangkat berhasil disimpan',
    'success.settings.saved': 'Pengaturan berhasil disimpan',
    'success.settings.apiKey.saved': 'Kunci API berhasil disimpan',
    'success.settings.hints.enabled': 'Petunjuk diaktifkan',
    'success.settings.hints.disabled': 'Petunjuk dinonaktifkan',
    'success.configuration.saved': 'Konfigurasi berhasil disimpan',
    'success.operation.completed': 'Operasi berhasil diselesaikan',
    'success.plugins.disabled': 'Pengaturan berhasil disimpan',
    'success.config.update.notification': 'Perintah pembaruan konfigurasi telah dikirim ke perangkat',
    'success.config.update.device.app.settings.notification': 'Perintah untuk memperbarui pengaturan aplikasi telah dikirim ke perangkat.',

    'form.icon.title': 'Ikon',
    'form.icon.name': 'Nama',
    'form.icon.file': 'Berkas',

    'configuration.add.warning': 'Anda yakin ingin membuat konfigurasi kosong? Anda harus menambahkan semua aplikasi sistem yang diperlukan secara manual. Sebaiknya salin dan modifikasi konfigurasi yang sudah ada.',
    'configuration.remove.warning': 'Anda yakin ingin menghapus konfigurasi terakhir? Anda akan kehilangan informasi aplikasi sistem mana yang diperlukan.',
    'form.configuration.title': 'Konfigurasi',
    'form.configuration.title.typical': 'Konfigurasi umum',
    'form.configuration.settings.auto.update': 'Pembaruan Otomatis',
    'form.configuration.settings.system.update': 'Pembaruan Sistem',
    'form.configuration.settings.system.update.default': 'Bawaan',
    'form.configuration.settings.system.update.immediate': 'Segera',
    'form.configuration.settings.system.update.scheduled': 'Terjadwal',
    'form.configuration.settings.system.update.postponed': 'Ditunda',
    'form.configuration.settings.system.update.time': 'Waktu pemasangan',
    'form.configuration.settings.system.update.time.from': 'dari:',
    'form.configuration.settings.system.update.time.to': 'sampai:',
    'form.configuration.settings.system.schedule.app.update': 'Jadwalkan pembaruan aplikasi',
    'form.configuration.settings.system.app.update.time': 'Waktu pembaruan aplikasi',
    'form.configuration.settings.download.updates': 'Unduh konten',
    'form.configuration.settings.download.updates.unlimited': 'Tanpa batas',
    'form.configuration.settings.download.updates.limited': '3 percobaan di jaringan seluler',
    'form.configuration.settings.download.updates.wifi': 'Hanya melalui WiFi',
    'form.configuration.settings.block.status.bar': 'Kunci bilah status',
    'form.configuration.settings.block.status.bar.hint': 'Pengaturan ini usang dan bekerja baik pada Android 6 ke bawah. Untuk mengunci bilah status pada versi Android yang lebih baru, gunakan mode kiosk (pengaturan MDM).',
    'form.configuration.settings.mdm.kiosk.mode': 'Mode kiosk',
    'form.configuration.settings.mdm.app.main': 'Aplikasi MDM',
    'form.configuration.settings.mdm.component.event.receiver': 'Kelas admin receiver',
    'form.configuration.settings.mdm.component.event.receiver.placeholder': 'Seharusnya com.hmdm.launcher.AdminReceiver',
    'form.configuration.settings.mdm.component.wifi.ssid': 'SSID WiFi',
    'form.configuration.settings.mdm.component.wifi.ssid.placeholder': 'SSID WiFi pendaftaran - kosongkan untuk memasukkan manual',
    'form.configuration.settings.mdm.component.wifi.password': 'Kata sandi WiFi',
    'form.configuration.settings.mdm.component.wifi.password.placeholder': 'Kata sandi WiFi pendaftaran - kosongkan untuk memasukkan manual',
    'form.configuration.settings.mdm.component.wifi.security': 'Jenis keamanan WiFi',
    'form.configuration.settings.mdm.component.wifi.notice': 'Catatan: pengaturan WiFi ini hanya diterapkan pada pendaftaran awal!',
    'form.configuration.settings.mdm.component.server.url': 'URL server baru',
    'form.configuration.settings.mdm.component.server.url.placeholder': 'Digunakan untuk migrasi ke server MDM baru',
    'form.configuration.settings.mdm.app.content': 'Aplikasi konten',
    'form.configuration.settings.mdm.kiosk.home': 'Aktifkan tombol Beranda',
    'form.configuration.settings.mdm.kiosk.recents': 'Aktifkan tombol Terkini',
    'form.configuration.settings.mdm.kiosk.notifications': 'Aktifkan notifikasi',
    'form.configuration.settings.mdm.kiosk.system.info': 'Aktifkan info bilah status',
    'form.configuration.settings.mdm.kiosk.keyguard': 'Aktifkan kunci layar',
    'form.configuration.settings.mdm.kiosk.lock.buttons': 'Kunci tombol Daya',
    'form.configuration.settings.mdm.mobile.enrollment': 'Daftar menggunakan data seluler',
    'form.configuration.settings.mdm.encrypt.device': 'Enkripsi penyimpanan perangkat',
    'form.configuration.settings.mdm.lock.safe.settings': 'Kunci pengaturan aman (WiFi, GPS, dll)',
    'form.configuration.settings.mdm.permissive': 'Mode permisif (tidak terkunci)',
    'form.configuration.settings.mdm.kiosk.exit': 'Tombol keluar kiosk',
    'form.configuration.settings.mdm.kiosk.screen': 'Layar selalu menyala',
    'form.configuration.settings.mdm.allowed.classes': 'Aktivitas yang diizinkan',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'Kelas dipisah koma, mis.: com.android.settings.homepage.SettingsHomepageActivity',
    'form.configuration.settings.mdm.restrictions': 'Batasan',
    'form.configuration.settings.mdm.restrictions.placeholder': 'Batasan MDM, dipisah koma, mis.: no_sms,no_outgoing_calls,no_usb_file_transfer',
    'form.configuration.settings.mdm.launcher': 'Ganti URL peluncur',
    'form.configuration.settings.mdm.launcher.placeholder': 'URL peluncur alternatif untuk pendaftaran di jaringan tertutup',
    'form.configuration.settings.mdm.misc': 'Entri kode QR lainnya',
    'form.configuration.settings.mdm.misc.placeholder': 'entri dipisah koma, mis.:\n"android.app.extra.PROVISIONING_LOCALE": "id_ID"',
    'form.configuration.settings.mdm.extras': 'Ekstra admin',
    'form.configuration.settings.mdm.extras.placeholder': 'pengaturan MDM ekstra dipisah koma, mis.:\n"com.hmdm.OPEN_WIFI": true',
    'form.configuration.settings.mdm.permissive.locked': 'Matikan mode kiosk untuk mengaktifkan opsi mode permisif',
    'form.configuration.settings.mdm.qrcode.url': 'URL kode QR',
    'form.configuration.settings.mdm.hint': 'Pilih aplikasi dan komponen utama',
    'form.configuration.apps.search.label': 'Cari:',
    'form.configuration.apps.sort.label': 'Urutkan:',
    'form.configuration.apps.sort.byname': 'Berdasarkan nama',
    'form.configuration.apps.sort.bypkg': 'Berdasarkan ID',
    'form.configuration.apps.no.apk': 'tidak ada',
    'form.configuration.apps.show.systeam.apps': 'Tampilkan Aplikasi Sistem',
    'form.configuration.apps.action.select': '(pilih)',
    'form.configuration.apps.action.install': 'Pasang',
    'form.configuration.apps.action.prohibit': 'Blokir',
    'form.configuration.apps.action.not.install': 'Jangan pasang',
    'form.configuration.apps.action.delete': 'Hapus',
    'form.configuration.apps.action.permit': 'Izinkan',
    'form.configuration.apps.label.inherit': 'Diwarisi',
    'form.configuration.apps.label.show': 'Tampilkan',
    'form.configuration.apps.label.not.show': 'Sembunyikan',
    'form.configuration.apps.edit.details': 'Parameter tambahan',
    'form.configuration.apps.keycode': 'Kode tombol',
    'form.configuration.apps.bottom': 'Tampilkan di baris bawah',
    'form.configuration.apps.long.tap': 'Tekan lama membuka pengaturan',
    'form.configuration.apps.hint': 'Petunjuk: untuk melepas aplikasi dari konfigurasi, pilih tindakan "Blokir" atau "Jangan pasang".',
    'form.configuration.settings.design.use.default': 'Gunakan desain bawaan',
    'form.configuration.settings.design.color.background': 'Warna Latar Belakang',
    'form.configuration.settings.design.color.background.placeholder': 'Pilih warna',
    'form.configuration.settings.design.color.app.names': 'Warna Nama Aplikasi',
    'form.configuration.settings.design.color.app.names.placeholder': 'Pilih warna',
    'form.configuration.settings.design.background.image.url': 'URL gambar latar belakang',
    'form.configuration.settings.design.background.image.url.placeholder': 'Masukkan url gambar latar belakang',
    'form.configuration.settings.design.icon': 'Ukuran ikon',
    'form.configuration.settings.design.icon.small': 'Kecil',
    'form.configuration.settings.design.icon.medium': 'Sedang (+ 20%)',
    'form.configuration.settings.design.icon.large': 'Besar (+ 40%)',
    'form.configuration.settings.design.desktop.header': 'Judul desktop',
    'form.configuration.settings.design.desktop.header.no': 'Tidak',
    'form.configuration.settings.design.desktop.header.deviceid': 'ID Perangkat',
    'form.configuration.settings.design.desktop.header.description': 'Deskripsi',
    'form.configuration.settings.design.desktop.header.custom': 'Templat khusus',
    'form.configuration.settings.design.desktop.header.hint': 'Pastikan parameter ini dikirim ke perangkat (Pengaturan - Pengaturan umum dan bahasa)',
    'form.configuration.settings.design.desktop.header.template': 'Masukkan templat',
    'form.configuration.settings.design.desktop.header.template.placeholder': 'Gunakan variabel',
    'form.configuration.settings.design.display.status': 'Tampilkan waktu dan status baterai',
    'form.configuration.settings.design.upload': 'Unggah',
    'form.configuration.settings.common.name': 'Nama',
    'form.configuration.settings.common.name.placeholder': 'Masukkan nama konfigurasi',
    'form.configuration.settings.common.desc': 'Deskripsi',
    'form.configuration.settings.common.desc.placeholder': 'Masukkan deskripsi konfigurasi',
    'form.configuration.settings.common.admin.pwd': 'Kata sandi buka kunci',
    'form.configuration.settings.common.admin.pwd.placeholder': 'Masukkan kata sandi buka kunci perangkat',
    'form.configuration.settings.common.gps': 'GPS',
    'form.configuration.settings.common.gps.any': 'Apa saja',
    'form.configuration.settings.common.gps.off': 'Nonaktif',
    'form.configuration.settings.common.gps.on': 'Aktif',
    'form.configuration.settings.common.bluetooth': 'Bluetooth',
    'form.configuration.settings.common.wifi': 'Wi-Fi',
    'form.configuration.settings.common.mobile.data': 'Data seluler',
    'form.configuration.settings.common.usb.storage': 'Blokir penyimpanan USB',
    'form.configuration.settings.common.brightness': 'Kelola kecerahan',
    'form.configuration.settings.common.brightness.none': 'Tidak ada',
    'form.configuration.settings.common.brightness.auto': 'Otomatis',
    'form.configuration.settings.common.brightness.manual': 'Nilai',
    'form.configuration.settings.common.brightness.value': 'Kecerahan layar',
    'form.configuration.settings.common.timeout': 'Kelola batas waktu layar',
    'form.configuration.settings.common.timeout.value': 'Batas waktu layar (dtk)',
    'form.configuration.settings.common.volume.block': 'Kunci volume',
    'form.configuration.settings.common.volume.manage': 'Kelola volume',
    'form.configuration.settings.common.volume.value': 'Volume',
    'form.configuration.settings.common.timezone.mode': 'Kelola zona waktu',
    'form.configuration.settings.common.timezone.mode.default': 'Jangan kelola',
    'form.configuration.settings.common.timezone.mode.auto': 'Otomatis',
    'form.configuration.settings.common.timezone.mode.manual': 'Manual',
    'form.configuration.settings.common.timezone': 'Zona waktu',
    'form.configuration.settings.common.timezone.placeholder': 'mis. Asia/Jakarta',
    'form.configuration.settings.common.timezone.link': 'Daftar zona waktu',
    'form.configuration.settings.common.no.network.warning': 'PERINGATAN! Jangan matikan semua saluran koneksi, jika tidak Anda tidak akan bisa mengelola perangkat lagi!',
    'form.configuration.settings.common.autostart.foreground': 'Jalankan otomatis aplikasi di latar depan',
    'form.configuration.settings.request.updates': 'Pelacakan Lokasi',
    'form.configuration.settings.request.updates.donottrack': 'Tanpa pelacakan aktif (gunakan data lokasi aplikasi pihak ketiga)',
    'form.configuration.settings.request.updates.gps': 'Lacak lokasi via GPS',
    'form.configuration.settings.request.updates.wifi': 'Lacak lokasi via Wi-Fi (layanan Google harus aktif)',
    'form.configuration.settings.request.updates.prompt.gps': 'Untuk melacak lokasi via GPS, Anda perlu mengaktifkan GPS',
    'form.configuration.settings.request.updates.prompt.wifi': 'Untuk melacak lokasi via Wi-Fi, Anda perlu mengaktifkan Wi-Fi',
    'form.configuration.settings.revoke.location.permission': 'Tanpa izin lokasi',
    'form.configuration.settings.revoke.location.permission.hint': 'Jika diaktifkan, izin lokasi tidak akan diberikan ke agen MDM dan tidak dapat melacak lokasi perangkat',
    'form.configuration.settings.apps.permissions': 'Izin untuk aplikasi lain',
    'form.configuration.settings.apps.permissions.grant': 'Berikan otomatis semua izin',
    'form.configuration.settings.apps.permissions.ask.location': 'Berikan otomatis semua, tanyakan izin lokasi ke pengguna',
    'form.configuration.settings.apps.permissions.deny.location': 'Berikan otomatis semua, jangan berikan izin lokasi',
    'form.configuration.settings.apps.permissions.ask.all': 'Tanyakan semua izin ke pengguna',
    'form.configuration.settings.push.options' : 'Notifikasi Push',
    'form.configuration.settings.push.options.mqtt.worker' : 'Protokol MQTT (hemat baterai)',
    'form.configuration.settings.push.options.mqtt.alarm' : 'Protokol MQTT',
    'form.configuration.settings.push.options.polling' : 'HTTP polling',
    'form.configuration.settings.push.options.mqtt.worker.hint' : 'Mengirim pesan Push seketika saat perangkat aktif. Namun pesan bisa tertunda hingga beberapa jam dalam mode tidur. Jangan gunakan opsi ini pada perangkat mandiri. MQTT memakai port TCP 31000, aktifkan di firewall Anda.',
    'form.configuration.settings.push.options.mqtt.alarm.hint' : 'MQTT adalah protokol ringan yang memakai sumber daya minimal. MQTT memakai port TCP 31000, aktifkan di firewall Anda.',
    'form.configuration.settings.push.options.polling.hint' : 'Long polling mempertahankan koneksi HTTP yang dapat memakan lebih banyak sumber daya server. Tidak memerlukan port TCP selain HTTP(S).',
    'form.configuration.settings.push.options.keepalive' : 'Waktu Keep-Alive',
    'form.configuration.settings.minute.1' : '1 menit',
    'form.configuration.settings.minutes.2' : '2 menit',
    'form.configuration.settings.minutes.3' : '3 menit',
    'form.configuration.settings.minutes.5' : '5 menit',
    'form.configuration.settings.minutes.10' : '10 menit',
    'form.configuration.settings.minutes.15' : '15 menit',
    'form.configuration.settings.password.mode' : 'Persyaratan kata sandi',
    'form.configuration.settings.password.mode.any' : 'Tidak ada',
    'form.configuration.settings.password.mode.present' : 'Kata sandi ada',
    'form.configuration.settings.password.mode.easy' : 'Mudah (minimal 6 simbol)',
    'form.configuration.settings.password.mode.moderate' : 'Sedang (8+ simbol, huruf dan angka)',
    'form.configuration.settings.password.mode.strong' : 'Kuat (8+, huruf besar & kecil, angka, tanda)',
    'form.configuration.settings.show.wifi': 'Pengaturan WiFi saat kesalahan koneksi',
    'form.configuration.settings.use.default.launcher': 'Mode latar belakang',
    'form.configuration.settings.use.default.launcher.hint': 'Jangan gantikan peluncur sistem, hanya jalankan layanan MDM di latar belakang. Tidak disarankan dengan mode kiosk.',
    'form.configuration.settings.disable.screenshots': 'Nonaktifkan tangkapan layar',
    'form.configuration.settings.orientation': 'Kunci orientasi',
    'form.configuration.settings.orientation.none': 'Jangan kunci',
    'form.configuration.settings.orientation.portrait': 'Potret',
    'form.configuration.settings.orientation.landscape': 'Lanskap',
    'form.configuration.settings.files.default.path': 'Path bawaan pada perangkat',
    'form.configuration.files.search.label': 'Cari:',
    'form.configuration.files.action.upload': 'Unggah',
    'form.configuration.files.action.remove': 'Hapus',
    'form.configuration.files.variables': 'Konten variabel',
    'form.configuration.files.variables.hint': 'String DEVICE_NUMBER, IMEI, CUSTOM* akan diganti dengan nilainya',

    'form.configuration.file.name': 'Nama berkas',
    'form.configuration.file.select': 'Pilih berkas',
    'form.configuration.file.create': '(buat berkas baru)',
    'form.configuration.file.description': 'Deskripsi berkas',
    'form.configuration.file.description.placeholder': 'Opsional, untuk kemudahan Anda',
    'form.configuration.file.override.path': 'Ganti path',
    'form.configuration.file.override.path.title': 'Tentukan path perangkat khusus untuk konfigurasi ini saja',
    'form.configuration.file.path': 'Path pada perangkat',
    'form.configuration.file.path.placeholder': 'Tanpa path ke drive, mis. /my-app/image.jpg',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.url.placeholder': 'Jika berkas dihosting di sumber eksternal',
    'form.configuration.file.file': 'Berkas',
    'form.configuration.file.action': 'Tindakan',
    'form.configuration.file.action.prompt.1': 'Unggah',
    'form.configuration.file.action.prompt.2': 'Hapus',
    'form.configuration.file.remove.prompt.1': 'Berkas ini tidak akan disinkronkan lagi dengan perangkat',
    'form.configuration.file.remove.prompt.2': 'Hapus berkas dari server',

    'form.password.title': 'Ubah Kata Sandi',
    'form.password.label.user': 'Pengguna',
    'form.password.label.password.new': 'Kata sandi baru',
    'form.password.label.password.new.placeholder': 'Masukkan kata sandi baru',
    'form.password.label.password.confirm': 'Verifikasi',
    'form.password.label.password.confirm.placeholder': 'Masukkan kembali kata sandi baru',
    'form.password.length': 'Panjang minimal: ${length}. ',

    'form.application.type': 'Tipe',
    'form.application.type.option.web': 'Halaman web',
    'form.application.type.option.app': 'Aplikasi',
    'form.application.type.option.intent': 'Tindakan sistem',
    'form.application.intent': 'Tindakan',
    'form.application.intent.placeholder': 'Pilih tindakan',
    'form.application.url.hint': 'Gunakan file:///storage/emulated/0/... untuk membuat tautan ke berkas dan folder lokal',
    'form.application.pkg': 'ID Paket',
    'form.application.from.file': 'ditentukan dari berkas',
    'form.application.pkg.title': 'ID paket otomatis ditentukan saat Anda mengunggah berkas APK. ID paket yang dimasukkan manual hanya diperlukan untuk aplikasi sistem.',
    'form.application.pkg.placeholder': 'Contoh, com.android.camera',
    'form.application.disabled.arch': 'Khusus versi',
    'form.application.disabled.arch.title': 'Untuk menambahkan APK bagi arsitektur CPU berbeda, klik "Tambah", atau buka daftar versi aplikasi',
    'form.application.arch': 'Kode native',
    'form.application.arch.title': 'Sebagian aplikasi berisi kode yang dioptimalkan untuk arsitektur CPU tertentu. Dalam kasus ini, Anda perlu mengunggah dua APK (untuk arsitektur armeabi-v7a dan arm64-v8a)',
    'form.application.arch.universal': 'Tidak ada (APK universal)',
    'form.application.arch.armeabi': 'Kode native untuk armeabi-v7a',
    'form.application.arch.arm64': 'Kode native untuk arm64-v8a',
    'form.application.arch.no.split': 'APK universal',
    'form.application.arch.split': 'Split APK',
    'form.application.arch.warning': 'APK ini hanya dioptimalkan untuk ${arch} dan mungkin tidak bekerja di semua perangkat. Disarankan mengunggah APK lain yang dioptimalkan untuk arsitektur CPU lain. Untuk memakai APK ini di semua perangkat, pilih "APK universal".',
    'form.application.arch.success': 'Aplikasi ini berisi APK untuk kedua arsitektur CPU',
    'form.application.version.exists': 'APK untuk versi ini sudah ada',
    'form.application.url.armeabi': 'URL untuk armeabi-v7a',
    'form.application.url.arm64': 'URL untuk arm64-v8a',
    'form.application.name': 'Nama Aplikasi',
    'form.application.name.title': 'Anda akan melihat nama aplikasi dalam daftar. Kami sarankan menggunakan nama yang unik dan informatif.',
    'form.application.name.placeholder': 'Contoh, Kamera (Android)',
    'form.application.version': 'Versi',
    'form.application.version.placeholder': '0 untuk aplikasi prainstal',
    'form.application.version.title': 'Versi paket otomatis ditentukan saat Anda mengunggah berkas APK. Set ke 0 untuk aplikasi sistem.',
    'form.application.version.code': 'Kode Versi',
    'form.application.version.code.exists': 'Versi dengan kode yang sama sudah ada. Laporkan masalah ini ke pengembang aplikasi.',
    'form.application.system': 'Aplikasi prainstal',
    'form.application.system.title': 'Aplikasi sistem sudah prainstal di perangkat dan tidak memerlukan URL atau berkas. Set flag ini hanya jika Anda perlu mengaktifkan paket sistem tertentu.',
    'form.application.run.after.install': 'Jalankan setelah pemasangan',
    'form.application.run.after.install.title': 'Aplikasi dengan layanan latar belakang perlu dijalankan di latar depan minimal sekali.',
    'form.application.run.at.boot': 'Jalankan saat boot',
    'form.application.run.at.boot.title': 'Set flag ini jika Anda perlu menjalankan aplikasi di latar depan setelah boot. Flag ini tidak memengaruhi proses latar belakang.',
    'form.application.url': 'URL',
    'form.application.url.title': 'URL hanya diketik jika aplikasi Anda dihosting di sumber eksternal. Disarankan mengunggah berkas APK menggunakan kolom di bawah.',
    'form.application.url.disabled': 'URL diatur untuk setiap versi. Untuk mengubah URL, tutup jendela ini dan klik ikon "Versi".',
    'form.application.file': 'Berkas',
    'form.application.auto.update': 'Pembaruan Otomatis',
    'form.application.auto.update.title': 'Set flag ini untuk memperbarui semua konfigurasi tempat aplikasi terpasang. Gunakan hanya jika Anda 100% yakin aplikasi stabil.',
    'form.application.showLabel': 'Tampilkan Ikon',
    'form.application.showLabel.title': 'Flag ini menandakan apakah ikon aplikasi ditampilkan di peluncur. Opsi ini dapat ditimpa pada konfigurasi.',
    'form.application.use.kiosk': 'Buka di Peramban Kiosk',
    'form.application.use.kiosk.title': 'Set flag ini jika Anda ingin membuka halaman web di Peramban Kiosk tanpa kemungkinan mengubah alamat',
    'form.application.iconText': 'Teks Ikon',
    'form.application.iconText.placeholder': '(bawaan)',
    'form.application.versions.title': 'Versi aplikasi',
    'form.application.icon': 'Ikon',
    'form.application.icon.default': '(bawaan)',
    'form.application.icon.add': 'Tambah ikon',

    'form.application.setting.app': 'Aplikasi',
    'form.application.setting.app.placeholder': 'Pilih aplikasi',
    'form.application.setting.name': 'Atribut',
    'form.application.setting.value': 'Nilai',
    'form.application.setting.comment': 'Komentar',
    'form.application.setting.type': 'Tipe',
    'form.application.setting.readonly': 'Tidak berubah di perangkat',

    'form.application.configurations.app': 'Aplikasi',
    'form.application.configurations.configs': 'Konfigurasi',

    'form.configuration.copy.new.name': 'Nama baru',
    'form.configuration.copy.new.name.placeholder': 'Masukkan nama konfigurasi baru',

    'form.customer.name': 'ID Pelanggan',
    'form.customer.name.placeholder': 'Identifier organisasi untuk masuk',
    'form.customer.admin.name': 'Nama admin',
    'form.customer.firstname.placeholder': 'Nama depan',
    'form.customer.lastname.placeholder': 'Nama belakang',
    'form.customer.language': 'Bahasa',
    'form.customer.language.placeholder': 'Kosong untuk Inggris atau dua huruf kecil',
    'form.customer.apiKey': 'Kunci API',
    'form.customer.apiKey.placeholder': 'Masukkan kunci API',
    'form.customer.prefix': 'Prefiks',
    'form.customer.prefix.placeholder': 'Masukkan prefiks nomor perangkat',
    'form.customer.device.configuration': 'Konfigurasi perangkat',
    'form.customer.desc': 'Deskripsi',
    'form.customer.desc.placeholder': 'Masukkan deskripsi organisasi',
    'form.customer.copy.configuration': 'Salin konfigurasi',
    'form.customer.copy.design': 'Salin desain',
    'form.customer.type': 'Tipe pelanggan',
    'form.customer.status': 'Status pelanggan',
    'form.customer.expiry.time': 'Tanggal kedaluwarsa',
    'form.customer.device.limit': 'Batas perangkat',
    'form.customer.size.limit': 'Batas penyimpanan',
    'form.customer.size.limit.placeholder': 'Ukuran (Mb)',

    'form.device.number': 'Nomor',
    'form.device.number.locked': 'Tidak dapat mengubah nomor karena perubahan nomor sebelumnya belum selesai.',
    'form.device.migration.warning': 'Nomor perangkat akan diubah. Pastikan perangkat menyala dan daring.',
    'form.device.number.hint': 'Jangan gunakan karakter khusus',
    'form.device.desc': 'Deskripsi',
    'form.device.groups': 'Grup',
    'form.device.config': 'Konfigurasi',
    'form.device.imei': 'IMEI',
    'form.device.phone.number': 'Nomor Telepon',

    'form.update.device.config': 'Konfigurasi',
    'form.update.device.action': 'Tindakan grup',
    'form.device.set.group': 'Tambahkan ke grup',
    'form.device.clear.group': 'Hapus dari grup',

    'form.file.file': 'Berkas',
    'form.file.name': 'Nama berkas',
    'form.file.description': 'Deskripsi (opsional)',
    'form.file.external': 'Eksternal',
    'form.file.external.title': 'Alih-alih mengunggah berkas, Anda dapat menentukan URL pada sumber eksternal',
    'form.file.external.url': 'URL',
    'form.file.external.url.placeholder': 'URL berkas pada sumber eksternal',
    'form.file.path': 'Path pada server',
    'form.file.device.path': 'Path pada perangkat',
    'form.file.device.path.placeholder': 'Path relatif terhadap /storage/emulated/0',
    'form.file.deleted': 'DIHAPUS',
    'form.file.copy.link': 'Salin tautan: ${link}',
    'form.file.configurations.file': 'Berkas',
    'form.file.configurations.configs': 'Konfigurasi',
    'form.file.configurations.upload': 'Unggah',
    'form.file.path.placeholder': 'Masukkan path relatif, contoh "/files/"',
    'form.file.available': 'Ruang tersedia: ${space} Mb',

    'form.file.apps.name': 'Nama Aplikasi',
    'form.file.apps.pkg': 'ID Paket',
    'form.file.apps.version': 'Versi',

    'form.group.name': 'Nama',
    'form.group.name.placeholder': 'Masukkan nama grup',

    'form.role.name': 'Nama',
    'form.role.name.placeholder': 'Masukkan nama peran',
    'form.role.permissions': 'Izin',

    'form.user.login': 'Login',
    'form.user.login.placeholder': 'Masukkan login pengguna',
    'form.user.name': 'Nama',
    'form.user.name.placeholder': 'Nama depan dan belakang',
    'form.user.email': 'Email',
    'form.user.email.placeholder': 'Masukkan email',
    'form.user.role': 'Peran',
    'form.user.all.devices.available': 'Semua perangkat tersedia',
    'form.user.available.groups': 'Grup perangkat yang tersedia',
    'form.user.all.configs.available': 'Semua konfigurasi tersedia',
    'form.user.available.configs': 'Konfigurasi yang tersedia',
    'form.user.password.new': 'Kata Sandi Baru',
    'form.user.password': 'Kata sandi',
    'form.user.password.new.placeholder': 'Masukkan kata sandi baru',
    'form.user.password.confirm': 'Verifikasi',
    'form.user.password.confirm.placeholder': 'Masukkan kembali kata sandi baru',

    'form.settings.hints.title': 'Petunjuk',

    'form.settings.plugins.title': 'Plugin yang Digunakan',

    'form.settings.common.title': 'Tampilan Tabel Perangkat',
    'form.settings.common.visible.columns': 'Kolom yang terlihat di tabel "Perangkat"',
    'form.settings.common.status': 'Status',
    'form.settings.common.role': 'Peran pengguna',
    'form.settings.common.date': 'Tanggal daring terakhir',
    'form.settings.common.device.number': 'Nomor perangkat',
    'form.settings.common.imei': 'IMEI',
    'form.settings.common.phone.number': 'Nomor Telepon',
    'form.settings.common.phone.model': 'Model Ponsel',
    'form.settings.common.status.permissions': 'Status Izin',
    'form.settings.common.status.installation': 'Status Pemasangan',
    'form.settings.common.status.files': 'Status Berkas',
    'form.settings.common.config': 'Konfigurasi',
    'form.settings.common.desc': 'Deskripsi',
    'form.settings.common.group': 'Grup',
    'form.settings.common.launcher.version': 'Versi peluncur',
    'form.settings.common.battery.level': 'Tingkat baterai',
    'form.settings.common.default.launcher': 'Mode latar belakang',
    'form.settings.common.mdm.mode': 'Mode MDM',
    'form.settings.common.kiosk.mode': 'Mode kiosk',
    'form.settings.common.android.version': 'Versi Android',
    'form.settings.common.enrollment.date': 'Tanggal pendaftaran',
    'form.settings.common.serial': 'Nomor seri',
    'form.settings.common.publicip': 'Alamat IP',

    'form.settings.design.title': 'Desain Bawaan',
    'form.settings.design.color.font': 'Warna Latar Belakang',
    'form.settings.design.color.font.placeholder': 'Pilih warna',
    'form.settings.design.color.app.names': 'Warna Nama Aplikasi',
    'form.settings.design.color.app.names.placeholder': 'Pilih warna',
    'form.settings.design.url.background.image': 'URL gambar latar belakang',
    'form.settings.design.url.background.image.placeholder': 'Masukkan URL gambar latar belakang',
    'form.settings.design.size.icon': 'Ukuran ikon',
    'form.settings.design.size.icon.small': 'Kecil',
    'form.settings.design.size.icon.medium': 'Sedang (+ 20%)',
    'form.settings.design.size.icon.large': 'Besar (+ 40%)',
    'form.settings.design.desktop.header': 'Judul desktop',
    'form.settings.design.desktop.header.no': 'Tidak',
    'form.settings.design.desktop.header.device.id': 'ID Perangkat',

    'form.settings.lang.title': 'Pengaturan bahasa',
    'form.settings.lang.use.default': 'Gunakan bahasa bawaan',
    'form.settings.lang.use': 'Gunakan bahasa',
    'form.settings.lang.id': 'Indonesia',
    'form.settings.lang.en': 'English',
    'form.settings.lang.pt': 'Português',
    'form.settings.lang.ru': 'Русский',
    'form.settings.lang.fr': 'Français',
    'form.settings.lang.ar': 'عربي',
    'form.settings.lang.es': 'Español',
    'form.settings.lang.de': 'Deutsch',
    'form.settings.lang.cn': '繁体中文',
    'form.settings.lang.tw': '繁體中文',
    'form.settings.lang.ja': '日本',
    'form.settings.lang.tr': 'Türkçe',
    'form.settings.lang.vi': 'Tiếng Việt',
    'form.settings.lang.it': 'Italiano',

    'form.settings.misc.title': 'Pengaturan lain-lain',
    'form.settings.misc.phone.format': 'Format nomor telepon',
    'form.settings.misc.phone.format.placeholder': '+9 (999) 999-99-99',
    'form.settings.misc.custom.property.name.1': 'Properti khusus #1',
    'form.settings.misc.custom.property.name.2': 'Properti khusus #2',
    'form.settings.misc.custom.property.name.3': 'Properti khusus #3',
    'form.settings.misc.custom.property.multiline': 'Multibaris',
    'form.settings.misc.custom.property.send': 'Kirim ke perangkat',
    'form.settings.misc.custom.property.name.placeholder': 'Masukkan nama untuk properti khusus',
    'form.settings.misc.create.new.devices': 'Tambah perangkat pada akses pertama',
    'form.settings.misc.new.device.config': 'Konfigurasi perangkat baru',
    'form.settings.misc.new.device.group': 'Grup perangkat baru',
    'form.settings.misc.send.description': 'Kirim deskripsi ke perangkat',
    'form.settings.misc.password.length': 'Panjang kata sandi minimal',
    'form.settings.misc.password.strength': 'Kekuatan kata sandi',
    'form.settings.misc.password.none': 'Tidak ditentukan (karakter apa saja)',
    'form.settings.misc.password.alphanumeric': 'Huruf besar dan kecil, angka',
    'form.settings.misc.password.specialchar': 'Huruf besar dan kecil, angka, karakter khusus',
    'form.settings.misc.password.reset': 'Pengguna harus menyetel ulang kata sandi',
    'form.settings.misc.idle.logout': 'Keluar saat diam',
    'form.settings.misc.idle.logout.never': 'Tidak pernah',
    'form.settings.misc.idle.logout.1': '5 menit',
    'form.settings.misc.idle.logout.2': '10 menit',
    'form.settings.misc.idle.logout.3': '30 menit',
    'form.settings.misc.idle.logout.4': '1 jam',
    'form.settings.security.title': 'Pengaturan keamanan',

    'idle.logout.message': 'Anda akan keluar dalam ${sec} detik karena tidak aktif',
    'idle.logout.resume': 'Saya di sini!',

    'form.settings.groups.title': 'Grup',
    'form.settings.groups.search.placeholder': 'Cari grup',

    'form.settings.users.title': 'Pengguna',
    'form.settings.users.search.placeholder': 'Cari pengguna',

    'form.settings.roles.title': 'Peran pengguna',

    'form.settings.icons.title': 'Ikon',
    'form.settings.icons.search.placeholder': 'Cari ikon',

    'form.qr.device.number': 'Nomor perangkat',
    'form.qr.auto.create': 'Tambahkan ke daftar perangkat jika belum ada',
    'form.qr.number.use': 'Penetapan nomor perangkat',
    'form.qr.number.use.request': 'Nilai pengguna',
    'form.qr.number.use.imei': 'IMEI',
    'form.qr.number.use.serial': 'Nomor seri',
    'form.qr.number.hint': 'Kosongkan nomor perangkat untuk mengaktifkan penetapan nomor otomatis',
    'form.qr.groups': 'Tambahkan ke grup',
    'form.qr.button.json': 'Dapatkan JSON',
    'form.qr.device.number.placeholder': 'Masukkan ID perangkat ...',
    'form.qr.code.image.alt': 'Kode QR',

    'form.password.reset.title': 'Silakan atur kata sandi baru',
    'form.password.reset.invalid': 'Maaf, tautan setel ulang kata sandi ini tidak valid',
    'form.password.reset.submit': 'Atur kata sandi',

    'form.two.factor.auth.title': 'Autentikasi dua faktor',
    'form.two.factor.auth.hint': 'Untuk menyelesaikan pendaftaran, pasang aplikasi Authenticator di perangkat seluler Anda, pindai kode QR, buat dan masukkan kode verifikasi.',
    'form.two.factor.auth.code.invalid': 'Kode verifikasi tidak valid!',
    'form.two.factor.auth.code': 'Kode verifikasi',
    'form.two.factor.auth.code.hint': 'Kode 6 digit dari aplikasi authenticator',
    'form.two.factor.auth.code.error': 'Kode harus berupa angka 6 digit',
    'form.two.factor.auth.verify': 'Verifikasi',
    'form.two.factor.auth.settings.hint': 'Untuk mengatur autentikasi dua faktor, pasang aplikasi Authenticator di perangkat seluler Anda, pindai kode QR, buat dan masukkan kode verifikasi.',
    'form.two.factor.auth.set': 'Autentikasi dua faktor aktif',
    'form.two.factor.auth.reset': 'Autentikasi dua faktor nonaktif',
    'form.two.factor.auth.off.confirm': 'Apakah Anda ingin menonaktifkan autentikasi dua faktor? Setelah diaktifkan kembali, semua authenticator akan menjadi tidak valid.',

    'form.profile.title': 'Ubah kata sandi',
    'form.profile.password.old': 'Kata Sandi Lama',
    'form.profile.password.old.placeholder': 'Masukkan kata sandi lama',
    'form.profile.password.new': 'Kata Sandi Baru',
    'form.profile.password.new.placeholder': 'Masukkan kata sandi baru',
    'form.profile.password.confirm': 'Verifikasi',
    'form.profile.password.confirm.placeholder': 'Masukkan kembali kata sandi baru',

    'tab.customers': 'Organisasi',
    'tab.common.applications': 'Aplikasi Bersama',

    'tab.devices': 'Perangkat',
    'tab.applications': 'Aplikasi',
    'tab.configurations': 'Konfigurasi',
    'tab.files': 'Berkas',
    'tab.default.design': 'Desain Bawaan',
    'tab.common.settings': 'Tampilan Tabel Perangkat',
    'tab.users': 'Pengguna',
    'tab.roles': 'Peran',
    'tab.groups': 'Grup',
    'tab.icons': 'Ikon',
    'tab.language': 'Pengaturan umum dan bahasa',
    'tab.license': 'Lisensi',
    'tab.hints': 'Petunjuk',
    'tab.plugins': 'Plugin',

    'tab.configeditor.common.settings': 'Pengaturan umum',
    'tab.configeditor.design.settings': 'Pengaturan Desain',
    'tab.configeditor.applications': 'Aplikasi',
    'tab.configeditor.mdm.settings': 'Pengaturan MDM',
    'tab.configeditor.app.settings': 'Pengaturan Aplikasi',
    'tab.configeditor.files': 'Berkas',

    'search.placeholder.file': 'cari berkas',
    'search.placeholder.configuration': 'Cari konfigurasi',
    'search.placeholder.customer': 'Cari organisasi',
    'search.placeholder.application': 'Cari aplikasi',
    'search.placeholder.application.setting': 'Cari pengaturan aplikasi',
    'search.placeholder.device': 'Cari perangkat',
    'search.placeholder.address': 'Cari alamat',
    'search.placeholder.point': 'Cari lokasi',
    'search.placeholder.message': 'Cari pesan',
    'search.placeholder': 'Cari ...',
    'search.placeholder.from': 'Dari ...',
    'search.placeholder.to': 'Sampai ...',
    'search.placeholder.user': 'Ketik nama pengguna',

    'table.heading.customer.name': 'Nama',
    'table.heading.customer.desc': 'Deskripsi',
    'table.heading.customer.registration.time': 'Terdaftar',
    'table.heading.customer.last.login.time': 'Login terakhir',
    'table.heading.customer.actions': 'Tindakan',
    'table.heading.customer.type': 'Tipe',
    'table.heading.customer.expiry.time': 'Kedaluwarsa',
    'table.heading.customer.device.limit': 'Batas',
    'table.heading.customer.status': 'Status',

    'customer.new': 'Baru',
    'customer.active': 'Aktif',
    'customer.need.followup': 'Perlu tindak lanjut',
    'customer.followup.sent': 'Tindak lanjut terkirim',
    'customer.internal.test': 'Uji internal',
    'customer.developer': 'Pengembang',
    'customer.difficult': 'Sulit',
    'customer.pause': 'Jeda',
    'customer.inactive': 'Belum masuk',
    'customer.abandon': 'Ditinggalkan',
    'customer.onpremise': 'Uji coba on-premise',
    'customer.denial': 'Penolakan',
    'customer.client': 'Klien',

    'table.heading.configuration.name': 'Nama',
    'table.heading.configuration.desc': 'Deskripsi',
    'table.heading.configuration.actions': 'Tindakan',

    'table.heading.application.setting.app.pkg': 'ID Paket',
    'table.heading.application.setting.app.name': 'Nama Aplikasi',
    'table.heading.application.setting.name': 'Atribut',
    'table.heading.application.setting.value': 'Nilai',
    'table.heading.application.setting.comment': 'Komentar',
    'table.heading.application.setting.lastUpdate': 'Tanggal Pembuatan',

    'table.heading.file.url': 'URL',
    'table.heading.file.devicepath': 'Path pada perangkat',
    'table.heading.file.description': 'Deskripsi berkas',
    'table.heading.file.action': 'Tindakan',
    'table.heading.file.lastUpdate': 'Tanggal pembuatan',

    'table.heading.application.pkg': 'ID Paket',
    'table.heading.application.name': 'Nama Aplikasi',
    'table.heading.application.version': 'Versi',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'Ikon',
    'table.heading.application.actions': 'Tindakan',
    'table.heading.application.order': 'Urutan',

    'table.heading.device.status': 'Status',
    'table.heading.device.date': 'Tanggal',
    'table.heading.device.device.number': 'Nomor Perangkat',
    'table.heading.device.imei': 'IMEI',
    'table.heading.device.phone.number': 'Nomor Telepon',
    'table.heading.device.phone.model': 'Model Ponsel',
    'table.heading.device.status.permissions': 'Status Izin',
    'table.heading.device.status.installation': 'Status Pemasangan',
    'table.heading.device.status.files': 'Status berkas',
    'table.heading.device.configuration': 'Konfigurasi',
    'table.heading.device.desc': 'Deskripsi',
    'table.heading.device.group': 'Grup',
    'table.heading.device.launcher.version': 'Versi peluncur',
    'table.heading.device.battery.level': 'Tingkat baterai',
    'table.heading.device.default.launcher': 'Mode latar belakang',
    'table.heading.device.mdm.mode': 'Mode MDM',
    'table.heading.device.kiosk.mode': 'Mode kiosk',
    'table.heading.device.android.version': 'Versi Android',
    'table.heading.device.enrollment.date': 'Terdaftar',
    'table.heading.device.serial': 'Nomor seri',
    'table.heading.device.publicip': 'Alamat IP',
    'table.heading.device.actions': 'Tindakan',

    'table.heading.group.name': 'Nama',
    'table.heading.group.actions': 'Tindakan',

    'table.heading.role.name': 'Nama',
    'table.heading.role.actions': 'Tindakan',

    'table.heading.file.name': 'Nama berkas',
    'table.heading.file.comment': 'Deskripsi',
    'table.heading.file.device.path': 'Path pada perangkat',
    'table.heading.file.update.time': 'Diperbarui pada',
    'table.heading.file.external': 'Eksternal',
    'table.heading.file.variable': 'Variabel',
    'table.heading.file.remove': 'Hapus',
    'table.heading.file.remove.hint': 'Memaksa penghapusan berkas dari penyimpanan perangkat',
    'table.heading.file.path': 'Path',
    'table.heading.file.address': 'Alamat',
    'table.heading.file.size': 'Ukuran',
    'table.heading.file.actions': 'Tindakan',

    'table.heading.users.login': 'Login',
    'table.heading.users.name': 'Nama',
    'table.heading.users.role': 'Peran',
    'table.heading.users.actions': 'Tindakan',

    'table.heading.common.apps.customer': 'Organisasi',
    'table.heading.common.apps.pkg': 'ID Paket',
    'table.heading.common.apps.name': 'Nama Aplikasi',
    'table.heading.common.apps.version': 'Versi',
    'table.heading.common.apps.url': 'URL',
    'table.heading.common.apps.label': 'Ikon',
    'table.heading.common.apps.actions': 'Tindakan',

    'notfound.devices': 'Tidak ada perangkat untuk ditampilkan.',
    'notfound.files':' Daftar berkas kosong.',
    'notfound.configurations': 'Tidak ada konfigurasi ditemukan.',
    'notfound.customers': 'Organisasi tidak ditemukan.',
    'notfound.common.apps': 'Tidak ada aplikasi untuk ditampilkan.',
    'notfound.applications': 'Aplikasi tidak ditemukan',
    'notfound.groups':' Tidak ada grup ditemukan. Coba kueri lain.',
    'notfound.users':' Pengguna tidak ditemukan. Coba kueri lain.',
    'notfound.apps.for.display': 'Tidak ada aplikasi untuk ditampilkan.',
    'notfound.app.versions.for.display': 'Tidak ada versi untuk ditampilkan.',
    'notfound.roles':'Daftar peran kosong.',
    'notfound.icons':'Daftar ikon kosong.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

    'menu.about': 'Tentang',
    'menu.profile': 'Profil',
    'menu.panel.master': 'Panel Master',
    'menu.panel.main': 'Panel utama',
    'menu.logout': 'Keluar',
    'menu.functions': 'Fungsi',
    'menu.settings': 'Pengaturan',
    'menu.show.hints': 'Tampilkan petunjuk',

    'plugin.name.not.specified': '<< Nama fungsi belum ditentukan >>',

    'breadcrumb.summary': 'Ringkasan',
    'breadcrumb.devices': 'Perangkat',
    'breadcrumb.applications': 'Aplikasi',
    'breadcrumb.configurations': 'Konfigurasi',
    'breadcrumb.files': 'Berkas',
    'breadcrumb.default.design': 'Desain bawaan',
    'breadcrumb.common.settings': 'Tampilan Tabel Perangkat',
    'breadcrumb.language.settings': 'Bahasa dan Pengaturan Lain',
    'breadcrumb.license.settings': 'Lisensi',
    'breadcrumb.users': 'Pengguna',
    'breadcrumb.groups': 'Grup',
    'breadcrumb.hints': 'Petunjuk',
    'breadcrumb.plugins': 'Plugin',
    'breadcrumb.config.details': 'Detail',
    'breadcrumb.application.versions': 'Versi',

    'app.name': 'Al-Khwarizmi MDM',
    'app.vendor.name':"Al-Khwarizmi",
    'app.vendor.link':"https://al-khwarizmi.example",
    'app.description': 'adalah sistem manajemen perangkat seluler sumber terbuka',
    'app.title': 'Panel Web ${appName}',

    'box.show.my.apps.only': 'Tampilkan hanya aplikasi saya',
    'configuration.app.version.upgrade.message': 'Versi terpasang ${installedVersion}, versi tersedia ${latestVersion}',

    'about.line.1': 'Panel kontrol ${appName}',
    'about.line.2': 'MDM sumber terbuka untuk Android',
    'about.line.3': 'Versi ${versionNumber}',
    'about.line.4': 'Plugin terpasang',

    'common.app.clarification': 'Aplikasi ini bersifat publik dan tidak tersedia untuk diedit. Untuk menambah versi lain aplikasi ini, hubungi administrator.',

    'qrcode.help.line1': 'Untuk menyiapkan perangkat Android (versi 7 atau lebih tinggi) dalam mode terkelola (korporat):',
    'qrcode.help.line2': 'Setel ulang perangkat ke setelan pabrik',
    'qrcode.help.line3': 'Ketuk 7 kali di sembarang tempat pada layar awal (Anda harus masuk ke mode pemindaian kode QR tersembunyi)',
    'qrcode.help.line4': 'Ikuti instruksi perangkat: terima ketentuan, sambungkan ke Wi-Fi, pindai kode QR ini',
    'qrcode.help.line5': 'Kode QR dapat berisi ID perangkat untuk ${appName} (sehingga Anda tidak perlu memasukkannya di perangkat seluler). Untuk menyematkan ID perangkat ke kode QR, masukkan ID perangkat di layar ini dan klik "Perbarui".',

    'form.configuration.app.version.select.select.title': 'Pilih versi untuk dipasang',
    'form.configuration.app.version.select.version.check.off': 'Nonaktifkan pengecekan versi',
    'form.configuration.app.version.select.upgrade.warning': 'Tingkatkan aplikasi "${v1}" ke versi "${v3}" untuk konfigurasi "${v2}"?',
    'form.configuration.app.version.select.downgrade.warning': 'Menurunkan versi akan MENGHAPUS SEMUA APLIKASI INI di semua perangkat! Turunkan versi aplikasi "${v1}" ke versi "${v2}"? ',

    'hint.step.1': 'Klik di sini untuk memulai pendaftaran perangkat',
    'hint.step.2': 'Klik di sini untuk membuka kode QR',
    'hint.step.3': 'Klik di sini untuk melihat cara membuka pemindai kode QR di perangkat',
    'hint.step.4': 'Temukan ID perangkat yang tersedia di tab «Perangkat». Klik «Perbarui» untuk menyertakannya dalam kode QR.',

    'ie.browser.notice.1': 'Maaf, Internet Explorer tidak didukung.',
    'ie.browser.notice.2': 'Peramban yang disarankan untuk menggunakan ${appName} - <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop">Chrome</a>.',

    'form.resolved.duplicate.pkg.text1': 'ID Paket "${pkg}" sudah digunakan oleh aplikasi yang tercantum di bawah.',
    'form.resolved.duplicate.pkg.text2': 'Apakah Anda ingin menambahkan aplikasi baru atau versi baru dari aplikasi yang sudah ada?',
    'form.resolved.duplicate.pkg.text3': 'Versi baru untuk',
    'form.resolved.duplicate.pkg.text4': 'ID Paket "${pkg}" sudah digunakan oleh aplikasi ${apps}',
    'form.resolved.duplicate.pkg.text5': 'Anda yakin ingin mengubah ID paket?',

    'tooltip.usage.byconfigurations': 'Digunakan oleh konfigurasi',
    'tooltip.usage.byapps': 'Digunakan oleh aplikasi',
    'tooltip.usage.byicons': 'Digunakan oleh ikon',

    'form.devices.label.params.more': 'Lebih banyak parameter',
    'form.devices.label.params.less': 'Lebih sedikit parameter',
    'form.devices.label.installation.status': 'Status pemasangan',
    "format.devices.date.createTime": "dd/MM/yyyy HH:mm:ss",
    "format.devices.date.datePicker": "dd-MM-yyyy",
    'form.devices.fast.search': 'Pencarian cepat berdasarkan nomor',

    'form.devices.selection.install.status.default': 'Status pemasangan ...',
    'form.devices.selection.install.status.all': 'Semua',
    'form.devices.selection.install.status.success': 'Berhasil',
    'form.devices.selection.install.status.version.mismatch': 'Versi Tidak Cocok',
    'form.devices.selection.install.status.failure': 'Gagal',
    'form.devices.selection.imei.changed': 'IMEI baru saja berubah',

    'search.placeholder.launcher.version': 'Versi Peluncur',
    'error.date.range.invalid': 'Interval tanggal tidak valid',

    'form.selection.status.any': 'Nilai apa saja',
    'form.selection.status.all': 'Semua',
    'form.selection.status.yes': 'Ya',
    'form.selection.status.no': 'Tidak',

    'form.devices.selection.status': 'Status ...',
    'form.devices.selection.online': 'Daring',
    'form.devices.selection.offline': 'Luring',
    'form.devices.selection.number': 'Masukkan nomor',

    'form.devices.selection.online.status.custom': 'Masukkan waktu',
    'form.devices.selection.online.status.1': '15 menit',
    'form.devices.selection.online.status.2': '30 menit',
    'form.devices.selection.online.status.3': '1 jam',
    'form.devices.selection.online.status.4': '2 jam',
    'form.devices.selection.online.status.5': '6 jam',
    'form.devices.selection.online.status.6': '1 hari',
    'form.devices.selection.online.status.7': '2 hari',
    'form.devices.selection.online.status.8': '3 hari',
    'form.devices.selection.online.status.9': '1 minggu',
    'form.devices.selection.online.status.10': '1 bulan',

    'form.devices.selection.online.status.label': 'menit',
    'form.devices.status.ago': 'lalu',
    'form.devices.status.minutes': 'mnt',
    'form.devices.status.hours': 'jam',
    'form.devices.status.days': 'hr',
    'form.devices.status.weeks': 'minggu',
    'form.devices.status.months': 'bln',
    'form.devices.status.years': 'thn',

    'customer.type.demo': 'Demo',
    'customer.type.small': 'Profesional',
    'customer.type.corporate': 'Enterprise',
    'customer.type.master': 'Utama',

    'customer.type.options.all': 'Semua tipe',
    'customer.status.options.all': 'Semua status',

    'account.expiring': 'Akun Anda akan kedaluwarsa dalam ${days} hari. Hubungi penjual untuk memperbarui akun Anda.',
    'account.expired.short': 'Akun Anda telah kedaluwarsa!',
    'account.expired': 'Akun Anda telah kedaluwarsa. Hubungi penjual untuk memperbarui akun Anda.',
    'device.limit.achieved': 'Tidak dapat menambah perangkat karena Anda telah mencapai batas. Hapus beberapa perangkat atau hubungi penjual untuk menambah batas perangkat Anda.',

    'menu.updates': 'Periksa pembaruan',
    'updates.title': 'Pembaruan',
    'updates.disabled.custom': 'Versi kustom, perbarui secara manual',
    'updates.disabled.not_master': 'Minta penyedia hosting untuk memperbarui',
    'updates.disabled.multiple': 'Beberapa versi aplikasi, perbarui secara manual',
    'updates.disabled.error': 'Kesalahan internal server',
    'updates.disabled.download': 'Kesalahan saat mengunduh pembaruan',
    'updates.application': 'Aplikasi',
    'updates.current.version': 'Versi saat ini',
    'updates.available.version': 'Versi tersedia',
    'updates.downloaded': 'Terunduh',
    'updates.auto.update': 'Perbarui aplikasi seluler secara otomatis (gunakan dengan hati-hati di produksi!)',
    'updates.enable.stats': 'Kirim statistik penggunaan ke penyedia layanan untuk meningkatkan performa sistem',
    'updates.get': 'Dapatkan pembaruan',
    'updates.checking': 'Memeriksa pembaruan...',
    'updates.getting': 'Mengambil pembaruan...',
    'updates.success': 'Pembaruan selesai',
    'updates.web.hint': 'Untuk menyelesaikan pembaruan aplikasi web, jalankan skrip shell "/opt/hmdm/update-web-app.sh" di konsol SSH',

    'permission.edit_device_app_settings': 'Kelola pengaturan aplikasi khusus perangkat',
    'permission.plugins_customer_access_management': 'Kelola plugin yang tersedia',
    'permission.plugin_audit_access': 'Lihat log audit',
    'permission.plugin_contacts_access': 'Kelola kontak',
    'permission.plugin_deviceexport_access': 'Ekspor perangkat',
    'permission.plugin_deviceimport_access': 'Impor perangkat',
    'permission.plugin_deviceinfo_access': 'Lihat informasi detail perangkat',
    'permission.plugin_devicelocations_access': 'Lihat perangkat di peta',
    'permission.plugin_devicelocations_settings_access': 'Konfigurasi plugin peta',
    'permission.plugin_devicelog_access': 'Lihat log perangkat',
    'permission.plugin_devicereset_access': 'Setel ulang dan mulai ulang perangkat',
    'permission.plugin_licensing_access': 'Akses ke lisensi (usang)',
    'permission.plugin_messaging_send': 'Kirim pesan',
    'permission.plugin_messaging_delete': 'Hapus pesan terkirim',
    'permission.plugin_photo_remove_photo': 'Hapus foto',
    'permission.settings': 'Kelola pengaturan',
    'permission.configurations': 'Lihat konfigurasi',
    'permission.edit_devices': 'Ubah info perangkat',
    'permission.edit_device_desc': 'Ubah deskripsi perangkat',
    'permission.enroll_devices': 'Daftarkan perangkat via kode QR',
    'permission.plugin_apuppet_access': 'Kendali jarak jauh',
    'permission.plugin_knox_access': 'Plugin Knox',
    'permission.add_config': 'Tambah konfigurasi',
    'permission.copy_config': 'Gandakan konfigurasi',
    'permission.plugin_openvpn_access': 'Plugin OpenVPN',
    'permission.plugin_photo_access': 'Plugin Foto',
    'permission.push_api': 'Akses ke Push API',
    'permission.plugin_urlfilter_access': 'Penyaringan URL',
    'permission.plugin_push_send': 'Kirim pesan Push',
    'permission.plugin_push_delete': 'Hapus pesan Push',
    'permission.get_updates': 'Periksa pembaruan',
    'permission.plugin_xtra_access': 'Permintaan versi Premium',
    'permission.applications': 'Lihat aplikasi',
    'permission.edit_applications': 'Kelola aplikasi',
    'permission.edit_application_versions': 'Kelola versi aplikasi',
    'permission.files': 'Lihat berkas',
    'permission.edit_files': 'Kelola berkas',

    'yes': 'ya',
    'no': 'tidak'
};
